name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Menggunakan Ubuntu versi 22.04 yang stabil untuk Buildozer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: kivy/buildozer-action@master
      with:
        command: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
